- name: Deploy MERN App
  hosts: web
  become: true
  vars:
    app_dir: /home/ubuntu/TravelMemory
    backend_dir: "{{ app_dir }}/backend"
    frontend_dir: "{{ app_dir }}/frontend"
    db_host: "10.0.2.29"  # Update with the actual private IP of the database

  tasks:

    - name: Debug - Start Deployment
      debug:
        msg: "Starting deployment of the MERN App..."

    - name: Check if Node.js is installed
      shell: node -v
      register: node_version
      ignore_errors: true

    - name: Install Node.js and npm if missing
      apt:
        name: nodejs
        state: present
      when: node_version.rc != 0

    - name: Check if PM2 is installed
      shell: pm2 -v
      register: pm2_version
      ignore_errors: true

    - name: Install PM2 globally if missing
      npm:
        name: pm2
        global: yes
        state: present
      when: pm2_version.rc != 0

    - name: Remove existing TravelMemory directory (if any)
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Clone MERN App Repository
      git:
        repo: "https://github.com/UnpredictablePrashant/TravelMemory.git"
        dest: "{{ app_dir }}"
        clone: yes
        update: yes

    - name: Install dependencies for backend
      shell: npm install
      args:
        chdir: "{{ backend_dir }}"

    - name: Install dependencies for frontend
      shell: npm install
      args:
        chdir: "{{ frontend_dir }}"

    - name: Build frontend (React)
      shell: npm run build
      args:
        chdir: "{{ frontend_dir }}"

    - name: Copy frontend build to backend
      shell: cp -r "{{ frontend_dir }}/build" "{{ backend_dir }}/public"

    - name: Create .env File for Backend
      copy:
        dest: "{{ backend_dir }}/.env"
        content: |
          PORT=5000
          MONGO_URI=mongodb://{{ db_host }}:27017/travelmemory
          JWT_SECRET=your_jwt_secret
          CLOUDINARY_NAME=your_cloudinary_name
          CLOUDINARY_API_KEY=your_cloudinary_api_key
          CLOUDINARY_API_SECRET=your_cloudinary_api_secret

    - name: Start MERN App using PM2
      shell: pm2 start server.js --name "mern-app"
      args:
        chdir: "{{ backend_dir }}"

    - name: Ensure PM2 starts on reboot
      shell: pm2 startup systemd && pm2 save

    - name: Debug - Deployment Completed
      debug:
        msg: "MERN App Deployment Completed Successfully!"
