- name: Database Server Setup
  hosts: db
  become: yes
  tasks:
    - name: Fix APT packages before MongoDB installation
      shell: |
        sudo apt update && sudo apt upgrade -y
        sudo apt --fix-broken install -y
        sudo apt autoremove -y
      args:
        executable: /bin/bash

    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Start MongoDB Service
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: Allow remote MongoDB connections (Security Considerations!)
      shell: |
        sudo sed -i 's/bindIp: 127.0.0.1/bindIp: 0.0.0.0/g' /etc/mongodb.conf
        sudo systemctl restart mongodb
      args:
        executable: /bin/bash
