---
- name: Configure MongoDB on Private Server
  hosts: db
  become: true

  tasks:
    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Ensure MongoDB is running
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: Create MongoDB Admin User
      shell: |
        mongo <<EOF
        use admin
        db.createUser({user: "admin", pwd: "securepassword", roles:[{role: "userAdminAnyDatabase", db: "admin"}]})
        EOF
      args:
        executable: /bin/bash

    - name: Enable remote access for MongoDB
      replace:
        path: /etc/mongodb.conf
        regexp: 'bind_ip = 127.0.0.1'
        replace: 'bind_ip = 0.0.0.0'

    - name: Restart MongoDB
      service:
        name: mongodb
        state: restarted

